cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "moncho/dry"
tap "neovim/neovim"
tap "universal-ctags/universal-ctags"
brew "bat"
brew "diff-so-fancy"
brew "fd"
brew "fzf"
brew "ghq"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "go"
brew "hub"
brew "jq"
brew "neovim"
brew "python"
brew "python@2"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rlwrap"
brew "rust"
brew "shpotify"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh", args: ["without-etcdir"]
brew "moncho/dry/dry"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
